name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Minikube
      uses: manusa/actions-setup-minikube@v2.4.0
      with:
        minikube-version: 'v1.23.0'
        kubernetes-version: 'v1.21.0'
        driver: docker

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.21.0'

    - name: Replace HARBOR_DOMAIN in deployment.yaml
      run: |
        sed -i 's|<HARBOR_DOMAIN>|${{ secrets.HARBOR_DOMAIN }}|g' /home/sam/netdevops/media-device-frontend/media-device-manager/deployment.yaml

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f /home/sam/netdevops/media-device-frontend/media-device-manager/deployment.yaml